export default [
  {
    q: 'The only place success comes before work is in the dictionary.',
    a: 'Vince Lombardi',
    c: '62',
    h: '<blockquote>&ldquo;The only place success comes before work is in the dictionary.&rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>',
  },
  {
    q: 'The biggest adventure is what lies ahead.',
    a: 'J.R.R. Tolkien',
    c: '41',
    h: '<blockquote>&ldquo;The biggest adventure is what lies ahead.&rdquo; &mdash; <footer>J.R.R. Tolkien</footer></blockquote>',
  },
  {
    q: 'The ladder of success is best climbed by stepping on the rungs of opportunity.',
    a: 'Ayn Rand',
    c: '78',
    h: '<blockquote>&ldquo;The ladder of success is best climbed by stepping on the rungs of opportunity.&rdquo; &mdash; <footer>Ayn Rand</footer></blockquote>',
  },
  {
    q: "Don't let the past steal your present.",
    a: 'Cherralea Morgen',
    c: '38',
    h: "<blockquote>&ldquo;Don't let the past steal your present.&rdquo; &mdash; <footer>Cherralea Morgen</footer></blockquote>",
  },
  {
    q: 'When you are tough on yourself, life is going to be infinitely easier on you.  ',
    a: 'Zig Ziglar',
    c: '79',
    h: '<blockquote>&ldquo;When you are tough on yourself, life is going to be infinitely easier on you.  &rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>',
  },
  {
    q: 'Time stays long enough for anyone who will use it.',
    a: 'Leonardo da Vinci',
    c: '50',
    h: '<blockquote>&ldquo;Time stays long enough for anyone who will use it.&rdquo; &mdash; <footer>Leonardo da Vinci</footer></blockquote>',
  },
  {
    q: 'When you view failure as feedback, you get more done. When you view failure as a finality, you get nothing done.',
    a: 'Jack Butcher',
    c: '112',
    h: '<blockquote>&ldquo;When you view failure as feedback, you get more done. When you view failure as a finality, you get nothing done.&rdquo; &mdash; <footer>Jack Butcher</footer></blockquote>',
  },
  {
    q: "Don't concern yourself with the money. Be of service. Build. Work. Dream. Create.",
    a: 'Earl Nightingale',
    c: '81',
    h: "<blockquote>&ldquo;Don't concern yourself with the money. Be of service. Build. Work. Dream. Create.&rdquo; &mdash; <footer>Earl Nightingale</footer></blockquote>",
  },
  {
    q: 'True wealth is of the heart, not of the purse.',
    a: 'Og Mandino',
    c: '46',
    h: '<blockquote>&ldquo;True wealth is of the heart, not of the purse.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>',
  },
  {
    q: "Don't let the silly little dramas of each day get you down. For you are here to do great things.",
    a: 'Ralph Marston',
    c: '96',
    h: "<blockquote>&ldquo;Don't let the silly little dramas of each day get you down. For you are here to do great things.&rdquo; &mdash; <footer>Ralph Marston</footer></blockquote>",
  },
  {
    q: 'Fear is your worst enemy. Risk is your best friend.',
    a: 'Gurbaksh Chahal',
    c: '51',
    h: '<blockquote>&ldquo;Fear is your worst enemy. Risk is your best friend.&rdquo; &mdash; <footer>Gurbaksh Chahal</footer></blockquote>',
  },
  {
    q: "If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.",
    a: 'Barack Obama',
    c: '106',
    h: "<blockquote>&ldquo;If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.&rdquo; &mdash; <footer>Barack Obama</footer></blockquote>",
  },
  {
    q: 'Sometimes it is harder to deprive oneself of a pain than of a pleasure.',
    a: 'F. Scott Fitzgerald',
    c: '71',
    h: '<blockquote>&ldquo;Sometimes it is harder to deprive oneself of a pain than of a pleasure.&rdquo; &mdash; <footer>F. Scott Fitzgerald</footer></blockquote>',
  },
  {
    q: "It's OK to have your eggs in one basket as long as you control what happens to that basket.",
    a: 'Elon Musk',
    c: '91',
    h: "<blockquote>&ldquo;It's OK to have your eggs in one basket as long as you control what happens to that basket.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>",
  },
  {
    q: 'If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man.',
    a: 'Mark Twain',
    c: '131',
    h: '<blockquote>&ldquo;If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>',
  },
  {
    q: 'He suffers more than necessary, who suffers before it is necessary.  ',
    a: 'Seneca',
    c: '69',
    h: '<blockquote>&ldquo;He suffers more than necessary, who suffers before it is necessary.  &rdquo; &mdash; <footer>Seneca</footer></blockquote>',
  },
  {
    q: 'When you know what you want, and you want it bad enough, you will find a way to get it.',
    a: 'Jim Rohn',
    c: '87',
    h: '<blockquote>&ldquo;When you know what you want, and you want it bad enough, you will find a way to get it.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>',
  },
  {
    q: 'Patience is a form of wisdom. It demonstrates that we understand and accept the fact that sometimes things must unfold in their own time.',
    a: 'Jon Kabat-Zinn',
    c: '137',
    h: '<blockquote>&ldquo;Patience is a form of wisdom. It demonstrates that we understand and accept the fact that sometimes things must unfold in their own time.&rdquo; &mdash; <footer>Jon Kabat-Zinn</footer></blockquote>',
  },
  {
    q: 'He who knows best knows how little he knows.',
    a: 'Thomas Jefferson',
    c: '44',
    h: '<blockquote>&ldquo;He who knows best knows how little he knows.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>',
  },
  {
    q: "Find your Light; They can't love you if they can't see you.",
    a: 'Bette Midler',
    c: '59',
    h: "<blockquote>&ldquo;Find your Light; They can't love you if they can't see you.&rdquo; &mdash; <footer>Bette Midler</footer></blockquote>",
  },
  {
    q: 'If there were no God, there would be no atheists.',
    a: 'Gilbert Chesterton',
    c: '49',
    h: '<blockquote>&ldquo;If there were no God, there would be no atheists.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>',
  },
  {
    q: 'The temptation to give up is strongest just before victory.',
    a: 'Zen Proverb',
    c: '59',
    h: '<blockquote>&ldquo;The temptation to give up is strongest just before victory.&rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>',
  },
  {
    q: 'In the long run, the sharpest weapon of all is a kind and gentle spirit.',
    a: 'Anne Frank',
    c: '72',
    h: '<blockquote>&ldquo;In the long run, the sharpest weapon of all is a kind and gentle spirit.&rdquo; &mdash; <footer>Anne Frank</footer></blockquote>',
  },
  {
    q: "Everyone has a sense of humor. If you don't laugh at jokes, you probably laugh at opinions.",
    a: 'Criss Jami',
    c: '91',
    h: "<blockquote>&ldquo;Everyone has a sense of humor. If you don't laugh at jokes, you probably laugh at opinions.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: 'The secret of getting started is breaking your complex, overwhelming tasks into small manageable tasks, and then starting on the first one.',
    a: 'Mark Twain',
    c: '139',
    h: '<blockquote>&ldquo;The secret of getting started is breaking your complex, overwhelming tasks into small manageable tasks, and then starting on the first one.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>',
  },
  {
    q: "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.",
    a: 'Ralph Marston',
    c: '109',
    h: "<blockquote>&ldquo;Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.&rdquo; &mdash; <footer>Ralph Marston</footer></blockquote>",
  },
  {
    q: 'Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.',
    a: 'Deepak Chopra',
    c: '129',
    h: '<blockquote>&ldquo;Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.&rdquo; &mdash; <footer>Deepak Chopra</footer></blockquote>',
  },
  {
    q: "Over time, loneliness gets inside you and doesn't go away.",
    a: 'Carlos Ruiz Zafon',
    c: '58',
    h: "<blockquote>&ldquo;Over time, loneliness gets inside you and doesn't go away.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: 'There are no secrets to success. It is the result of preparation, hard work, learning from failure.',
    a: 'Colin Powell',
    c: '99',
    h: '<blockquote>&ldquo;There are no secrets to success. It is the result of preparation, hard work, learning from failure.&rdquo; &mdash; <footer>Colin Powell</footer></blockquote>',
  },
  {
    q: 'Quiet people have the loudest minds.',
    a: 'Stephen Hawking',
    c: '36',
    h: '<blockquote>&ldquo;Quiet people have the loudest minds.&rdquo; &mdash; <footer>Stephen Hawking</footer></blockquote>',
  },
  {
    q: 'None but ourselves can free our minds.',
    a: 'Bob Marley',
    c: '38',
    h: '<blockquote>&ldquo;None but ourselves can free our minds.&rdquo; &mdash; <footer>Bob Marley</footer></blockquote>',
  },
  {
    q: 'In all chaos there is a cosmos, in all disorder a secret order.',
    a: 'Carl Jung',
    c: '63',
    h: '<blockquote>&ldquo;In all chaos there is a cosmos, in all disorder a secret order.&rdquo; &mdash; <footer>Carl Jung</footer></blockquote>',
  },
  {
    q: 'The way we feel is the direct result of what we think.',
    a: 'Peter A. Cohen',
    c: '54',
    h: '<blockquote>&ldquo;The way we feel is the direct result of what we think.&rdquo; &mdash; <footer>Peter A. Cohen</footer></blockquote>',
  },
  {
    q: "Don't think money does everything or you are going to end up doing everything for money.",
    a: 'Voltaire',
    c: '88',
    h: "<blockquote>&ldquo;Don't think money does everything or you are going to end up doing everything for money.&rdquo; &mdash; <footer>Voltaire</footer></blockquote>",
  },
  {
    q: 'You can have results or excuses, but not both.',
    a: 'Arnold Schwarzenegger',
    c: '46',
    h: '<blockquote>&ldquo;You can have results or excuses, but not both.&rdquo; &mdash; <footer>Arnold Schwarzenegger</footer></blockquote>',
  },
  {
    q: 'Truth is exact correspondence with reality. ',
    a: 'Paramahansa Yogananda',
    c: '44',
    h: '<blockquote>&ldquo;Truth is exact correspondence with reality. &rdquo; &mdash; <footer>Paramahansa Yogananda</footer></blockquote>',
  },
  {
    q: 'The most creative act you will ever undertake is the act of creating yourself.',
    a: 'Deepak Chopra',
    c: '78',
    h: '<blockquote>&ldquo;The most creative act you will ever undertake is the act of creating yourself.&rdquo; &mdash; <footer>Deepak Chopra</footer></blockquote>',
  },
  {
    q: 'I believe that potential is unlimited - success depends on daring to act on dreams.   ',
    a: 'Estee Lauder',
    c: '86',
    h: '<blockquote>&ldquo;I believe that potential is unlimited - success depends on daring to act on dreams.   &rdquo; &mdash; <footer>Estee Lauder</footer></blockquote>',
  },
  {
    q: 'We have to walk in a way that we only print peace and serenity on the Earth. Walk as if you are kissing the Earth with your feet.',
    a: 'Thich Nhat Hanh',
    c: '129',
    h: '<blockquote>&ldquo;We have to walk in a way that we only print peace and serenity on the Earth. Walk as if you are kissing the Earth with your feet.&rdquo; &mdash; <footer>Thich Nhat Hanh</footer></blockquote>',
  },
  {
    q: "You're on earth. There's no cure for that.",
    a: 'Samuel Beckett',
    c: '42',
    h: "<blockquote>&ldquo;You're on earth. There's no cure for that.&rdquo; &mdash; <footer>Samuel Beckett</footer></blockquote>",
  },
  {
    q: 'If you throw away all thoughts of attainment, you will then come to see the real purpose of your quest.',
    a: 'Seungsahn',
    c: '103',
    h: '<blockquote>&ldquo;If you throw away all thoughts of attainment, you will then come to see the real purpose of your quest.&rdquo; &mdash; <footer>Seungsahn</footer></blockquote>',
  },
  {
    q: "I know not all that may be coming, but be it what it will, I'll go to it laughing.",
    a: 'Herman Melville',
    c: '82',
    h: "<blockquote>&ldquo;I know not all that may be coming, but be it what it will, I'll go to it laughing.&rdquo; &mdash; <footer>Herman Melville</footer></blockquote>",
  },
  {
    q: "It's not what we do once in a while that shapes our lives, but what we do consistently.",
    a: 'Tony Robbins',
    c: '87',
    h: "<blockquote>&ldquo;It's not what we do once in a while that shapes our lives, but what we do consistently.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: 'If fear is too strong, the genius is suppressed.',
    a: 'Robert Kiyosaki',
    c: '48',
    h: '<blockquote>&ldquo;If fear is too strong, the genius is suppressed.&rdquo; &mdash; <footer>Robert Kiyosaki</footer></blockquote>',
  },
  {
    q: 'The people who succeed are irrationally passionate about something.',
    a: 'Naval Ravikant',
    c: '67',
    h: '<blockquote>&ldquo;The people who succeed are irrationally passionate about something.&rdquo; &mdash; <footer>Naval Ravikant</footer></blockquote>',
  },
  {
    q: 'You must conceive it in your heart and mind before you can receive it. If you believe then all things are possible.',
    a: 'Norman Vincent Peale',
    c: '115',
    h: '<blockquote>&ldquo;You must conceive it in your heart and mind before you can receive it. If you believe then all things are possible.&rdquo; &mdash; <footer>Norman Vincent Peale</footer></blockquote>',
  },
  {
    q: 'Those who bring sunshine into the lives of others cannot keep it from themselves.',
    a: 'James Matthew Barrie',
    c: '81',
    h: '<blockquote>&ldquo;Those who bring sunshine into the lives of others cannot keep it from themselves.&rdquo; &mdash; <footer>James Matthew Barrie</footer></blockquote>',
  },
  {
    q: 'Your past does not equal your future.',
    a: 'Tony Robbins',
    c: '37',
    h: '<blockquote>&ldquo;Your past does not equal your future.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>',
  },
  {
    q: 'At first dreams seem impossible, then improbable, then inevitable.',
    a: 'Christopher Reeve',
    c: '66',
    h: '<blockquote>&ldquo;At first dreams seem impossible, then improbable, then inevitable.&rdquo; &mdash; <footer>Christopher Reeve</footer></blockquote>',
  },
  {
    q: "Don't be afraid to go slowly. Be afraid of stopping.",
    a: 'Zen Proverb',
    c: '52',
    h: "<blockquote>&ldquo;Don't be afraid to go slowly. Be afraid of stopping.&rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
];
